spring.application.name=KomunikacjaMiejska
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=IKOPKA
spring.datasource.password=qazwsx
#--- idk czy to wogóle jest potrzebne
logging.level.root=INFO
#
#--- a to podobno do po??czenia zdalnego z ora3elka.pw.edu.pl, idk czy dzia?a?yby 2 na raz wi?c wstawiam zakomentowane
#spring.datasource.url=jdbc:oracle:thin:@ora3.elka.pw.edu.pl:1521:ora3inf
#spring.datasource.username=tm******
#spring.datasource.password=tm******
#logging.level.root=INFO

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.thymeleaf.cache=false

spring.web.error.whitelabel.enabled=false